name: familytree
description: A clothing and fashion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.0
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.0
  firebase_database: ^6.1.0
  google_sign_in: ^5.0.0
  fluttertoast: ^7.1.8
  email_validator: ^1.0.6
  cached_network_image:
  permission_handler: ^6.1.0
  image_picker: ^0.7.5+3
  graphview: ^0.7.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logowhite.png
    - assets/images/login_bg.png
    - assets/images/father.png
    - assets/images/mother.png
    - assets/images/sister.png
    - assets/images/brother.png
    - assets/images/child.png
    - assets/images/husband.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

